name = "MechGlueDiffEqBase"
uuid = "2532746b-52b5-4539-9431-8bb183ab067f"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]
version = "0.2.5"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Unitfu = "5ee08b94-2369-4f4a-b8c7-99333ba35fb0"

[compat]
julia = "1"

[targets]
test = ["Test"]
