name = "MechGlueDiffEqBase"
uuid = "2532746b-52b5-4539-9431-8bb183ab067f"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
